/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include"stdio.h"

#include"typedef"
#include"stdint.h"
#define RCC_BASE   0X40021000
#define GPIO_A  0X40010800
#define RCC_APB2ENR  *(vuint32_t*)(RCC_BASE+0X18)
#define GPIA_CRH  *(vuint32_t*)(GPIO_A+0X04)
#define  GPIA_ODR *(vuint32_t*)(GPIO_A+0X0C)

typedef union {
	vuint32_t allfilds;
	struct{
		vuint32_t reserved:13;
		vuint32_t p_13:1;
	}pin;
}r_odr_t;
volatile r_odr_t*   r_odr=(volatile r_odr_t*)(GPIO_A + 0X0C);
unsigned char g_varibls[3]={1,2,3};
unsigned char const const_varibls[3]={1,2,3};
unsigned char bss_var[3];
int main(void)
{
	RCC_APB2ENR|=(1<<2);
	GPIA_CRH&=0Xff0fffff;
	GPIA_CRH|=0X00200000;
	int i ;
	while(1){
		r_odr->pin.p_13=0;
		for( i=0;i<5000;i++);
		r_odr->pin.p_13=1;
		for( i=0;i<5000;i++);
	}
	return 0 ;
}
